### PR TITLE
add trace options to redis

### PR DESCRIPTION
**Pull request by yancl**
Do something like this in ocsql: https://github.com/opencensus-integrations/ocsql/pull/4

PTAL, Thanks

### CODE REVIEW

**Comment by odeke-em** [comment]
Nice, thank you @yancl! LGTM but just one request, could you please perhaps provide a note or simple example in the README. /cc @basvanbeek

**Comment by yancl** [comment]
Thanks for your review @odeke-em ! 

I add some test case and example, PTAL:)

**Review by odeke-em — APPROVED** [review]
Perfect, thank you @yancl! LGTM and welcome to OpenCensus integrations, hope you enjoy using these integrations and that are valuable. Please don't hesitate to report any bugs or feature requests!

**Comment by yancl** [comment]
Thank you for your great work:)

**Pull request merged**
