### PR TITLE
redis: add DoContext to Script type

### LINKED ISSUE #6: Support using ConnWithContext in *Script type
Hi! Just found this project. Great stuff!

Something I think it could benefit from is adding support for using a `ConnWithContext` to the `Script` type, so that `(*Script).Do(c Conn)` can automatically use a ConnWithContext if the input Conn implements it, or alternatively expose a `DoWithContext` which seems to be the convention.

What do you think?

### PR DESCRIPTION
**Pull request by johanbrandhorst**
Fixes #6 

I wasn't quite sure this was exactly how it ought to be done, but very open to discussion!

### CODE REVIEW

**Review by odeke-em — APPROVED** [review]
Nice, thank you @johanbrandhorst! LGTM but one suggestion would be to now replace `(s *Script) Do(` with
```go
func (s *Script) Do(c ConnWithContext, keysAndArgs ...interface{}) (interface{}, error) {
         return s.DoContext(context.Background(), c, keysAndArgs...) 
}
```

**Comment by johanbrandhorst** [comment]
Hey @odeke-em, I considered something like this but I was worried that it wouldn't work with the Conn type which is used elsewhere. This would be a compatibility breaking change but since you suggested it I'll go ahead and apply it :).

**Comment by johanbrandhorst** [comment]
Updated as suggested.

**Review by odeke-em — APPROVED** [review]
LGTM, thank you @johanbrandhorst!

**Pull request merged**
